# Oni Configuration File

## 日志等级 [ TRACE | DEBUG | INFO | WARNING | ERROR | FATAL ]
log_level: DEBUG

## Oni 端口 [ 1024 - 65535 ]
port: 5600

## MC 服务器地址
mc_server_ip: gtnh.akyuu.cn

## MC 服务器状态更新间隔 [ 秒 ]
mc_server_status_update_interval: 60

## 调试模式
debug: true